Test Event Name
test1

Response
{
  "errorMessage": "Syntax error in module 'lambda_function': expected 'except' or 'finally' block (lambda_function.py, line 29)",
  "errorType": "Runtime.UserCodeSyntaxError",
  "requestId": "",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\" Line 29\n    for voucher in retrieved_vouchers:\n"
  ]
}

Function Logs
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'lambda_function': expected 'except' or 'finally' block (lambda_function.py, line 29)
Traceback (most recent call last):
  File "/var/task/lambda_function.py" Line 29
    for voucher in retrieved_vouchers:INIT_REPORT Init Duration: 127.94 ms	Phase: init	Status: error	Error Type: Runtime.UserCodeSyntaxError
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'lambda_function': expected 'except' or 'finally' block (lambda_function.py, line 29)
Traceback (most recent call last):
  File "/var/task/lambda_function.py" Line 29
    for voucher in retrieved_vouchers:INIT_REPORT Init Duration: 1383.55 ms	Phase: invoke	Status: error	Error Type: Runtime.UserCodeSyntaxError
START RequestId: 6b389804-24a2-46c4-8b65-978be765778f Version: $LATEST
END RequestId: 6b389804-24a2-46c4-8b65-978be765778f
REPORT RequestId: 6b389804-24a2-46c4-8b65-978be765778f	Duration: 1408.12 ms	Billed Duration: 1409 ms	Memory Size: 128 MB	Max Memory Used: 43 MB	Status: error
