Test Event Name
test

Response
{
  "errorMessage": "An error occurred (ValidationException) when calling the GetItem operation: The provided key element does not match the schema",
  "errorType": "ClientError",
  "requestId": "a450ce6d-1e84-4e3f-a514-8526fb730304",
  "stackTrace": [
    "  File \"/var/task/lambda_function.py\", line 19, in lambda_handler\n    response = table.get_item(Key={'PNR': id_value})  # Assuming 'PNR' is your primary key\n",
    "  File \"/var/lang/lib/python3.12/site-packages/boto3/resources/factory.py\", line 581, in do_action\n    response = action(self, *args, **kwargs)\n",
    "  File \"/var/lang/lib/python3.12/site-packages/boto3/resources/action.py\", line 88, in __call__\n    response = getattr(parent.meta.client, operation_name)(*args, **params)\n",
    "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 565, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n",
    "  File \"/var/lang/lib/python3.12/site-packages/botocore/client.py\", line 1021, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"
  ]
}

Function Logs
START RequestId: a450ce6d-1e84-4e3f-a514-8526fb730304 Version: $LATEST
LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html
[ERROR] ClientError: An error occurred (ValidationException) when calling the GetItem operation: The provided key element does not match the schema
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 19, in lambda_handler
    response = table.get_item(Key={'PNR': id_value})  # Assuming 'PNR' is your primary key
  File "/var/lang/lib/python3.12/site-packages/boto3/resources/factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "/var/lang/lib/python3.12/site-packages/boto3/resources/action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "/var/lang/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/lang/lib/python3.12/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)END RequestId: a450ce6d-1e84-4e3f-a514-8526fb730304
REPORT RequestId: a450ce6d-1e84-4e3f-a514-8526fb730304	Duration: 2862.21 ms	Billed Duration: 2863 ms	Memory Size: 128 MB	Max Memory Used: 78 MB	Init Duration: 292.83 ms

Request ID
a450ce6d-1e84-4e3f-a514-8526fb730304
